package com.edda21.qp.adapter.in.messaging.kafka;

import java.util.Map;

/**
 * Represents a single question generated by the LLM.
 * This is the structured form of the raw LLM output
 * after parsing/validation on the Python side.
 */
public class LlmQuestionDto {

  /**
   * Plain question text shown to the student.
   */
  private String text;

  /**
   * Optional subject/topic (MATH, HISTORY, etc.).
   */
  private String subject;

  /**
   * Optional difficulty label (EASY, MEDIUM, HARD, etc.).
   */
  private String difficulty;

  /**
   * Optional metadata, for example: tags, explanation, correct answer,
   * answer options, etc. Structure is intentionally generic.
   */
  private Map<String, Object> metadata;

  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public String getDifficulty() {
    return difficulty;
  }

  public void setDifficulty(String difficulty) {
    this.difficulty = difficulty;
  }

  public Map<String, Object> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, Object> metadata) {
    this.metadata = metadata;
  }
}
